# -*- coding: utf-8 -*-
"""ankitjaiswal_202401100400037.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16JG5Gu369rDQhjwB2QX9n0na3WuGybnm
"""



import pandas as pd

# Load dataset
df = pd.read_csv('/content/drive/MyDrive/diabetes_dataset.csv')

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(10, 6))
sns.histplot(df['BMI'], kde=True, color='blue')
plt.title('BMI Distribution')
plt.xlabel('BMI')
plt.ylabel('Frequency')
plt.show()

plt.figure(figsize=(10, 6))
sns.scatterplot(x='Age', y='Glucose', data=df, hue='Outcome', palette='coolwarm')
plt.title('Age vs Glucose Levels')
plt.xlabel('Age')
plt.ylabel('Glucose')
plt.show()

plt.figure(figsize=(16, 14), dpi=200)
sns.heatmap(df.corr(numeric_only = True), annot = True)